// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// Defines values for GetItemsParamsOrderBy.
const (
	CreatedAtAsc  GetItemsParamsOrderBy = "created_at_asc"
	CreatedAtDesc GetItemsParamsOrderBy = "created_at_desc"
	NameAsc       GetItemsParamsOrderBy = "name_asc"
	NameDesc      GetItemsParamsOrderBy = "name_desc"
)

// Category defines model for Category.
type Category struct {
	Color string `json:"color"`
	Id    int32  `json:"id"`
	Name  string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Item defines model for Item.
type Item struct {
	CategoryId int32  `json:"category_id"`
	CreatedAt  string `json:"created_at"`
	Id         int32  `json:"id"`
	Name       string `json:"name"`
}

// Record defines model for Record.
type Record struct {
	Id    int32  `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetItemsParams defines parameters for GetItems.
type GetItemsParams struct {
	SearchPhrase *string               `form:"search_phrase,omitempty" json:"search_phrase,omitempty"`
	CategoryId   *int32                `form:"category_id,omitempty" json:"category_id,omitempty"`
	OrderBy      GetItemsParamsOrderBy `form:"order_by" json:"order_by"`
}

// GetItemsParamsOrderBy defines parameters for GetItems.
type GetItemsParamsOrderBy string

// CreateItemJSONBody defines parameters for CreateItem.
type CreateItemJSONBody struct {
	CategoryId int32  `json:"category_id"`
	Name       string `json:"name"`
}

// UpdateItemJSONBody defines parameters for UpdateItem.
type UpdateItemJSONBody struct {
	CategoryId int32  `json:"category_id"`
	Name       string `json:"name"`
}

// GetRecordsByItemParams defines parameters for GetRecordsByItem.
type GetRecordsByItemParams struct {
	ItemId int32 `form:"itemId" json:"itemId"`
}

// CreateRecordJSONBody defines parameters for CreateRecord.
type CreateRecordJSONBody struct {
	ItemId int32  `json:"item_id"`
	Name   string `json:"name"`
	Value  string `json:"value"`
}

// UpdateRecordJSONBody defines parameters for UpdateRecord.
type UpdateRecordJSONBody struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody CreateItemJSONBody

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody UpdateItemJSONBody

// CreateRecordJSONRequestBody defines body for CreateRecord for application/json ContentType.
type CreateRecordJSONRequestBody CreateRecordJSONBody

// UpdateRecordJSONRequestBody defines body for UpdateRecord for application/json ContentType.
type UpdateRecordJSONRequestBody UpdateRecordJSONBody
