// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Title   string `json:"title"`
}

// Item defines model for Item.
type Item struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}
