openapi: 3.0.4
info:
  title: Vault
  version: 1.0.0

paths:
  /items:
    get:
      operationId: GetItems
      responses:
        200:
          description: All items belonging to a user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: CreateItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        201:
          description: Newly created item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /items/{itemId}:
    delete:
      operationId: DeleteItem
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Deleted item
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: UpdateItem
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        200:
          description: Updated item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
       - message
      properties:
        message:
          type: string

    Item:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string


