openapi: 3.0.4
info:
  title: Vault
  version: 1.0.0

paths:
  /items:
    get:
      operationId: GetItems
      responses:
        200:
          description: All items belonging to a user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: CreateItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
                - name
      responses:
        201:
          description: Newly created item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /items/{itemId}:
    delete:
      operationId: DeleteItem
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: integer
            format: int32
      responses:
        204:
          description: Deleted item
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: UpdateItem
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
                - name
      responses:
        200:
          description: Updated item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /records:
    get:
      operationId: GetRecordsByItem
      parameters:
        - name: itemId
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: All records belonging to an item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  records:
                    type: array
                    items:
                      $ref: "#/components/schemas/Record"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: CreateRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                value:
                  type: string
                  minLength: 1
              required:
                - name
                - value
      responses:
        201:
          description: Newly created record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /records/{recordId}:
    delete:
      operationId: DeleteRecord
      parameters:
        - in: path
          name: recordId
          required: true
          schema:
            type: integer
            format: int32
      responses:
        204:
          description: Deleted record
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: UpdateRecord
      parameters:
        - in: path
          name: recordId
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                value:
                  type: string
                  minLength: 1
              required:
                - name
                - value
      responses:
        200:
          description: Updated record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    Error:
      type: object
      required:
       - message
      properties:
        message:
          type: string

    Item:
      type: object
      required:
        - id
        - name
        - createdAt
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        createdAt:
          type: string

    Record:
      type: object
      required:
        - id
        - name
        - value
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        value:
          type: string
