openapi: 3.0.4
info:
  title: Vault
  version: 1.0.0

paths:
  /items:
    get:
      operationId: GetItems
      responses:
        200:
          description: All items belonging to a user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
       - message
       - title
      properties:
        message:
          type: string
        title:
          type: string

    Item:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string


