// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	ID          int32
	Name        string
	Color       string
	ClerkUserID string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Item struct {
	ID          int32
	Name        string
	ClerkUserID string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CategoryID  sql.NullInt32
}

type Record struct {
	ID        int32
	Name      string
	Value     string
	ItemID    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
