// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: records.sql

package sqlc

import (
	"context"
)

const deleteRecords = `-- name: DeleteRecords :exec
UPDATE records
SET deleted_at = NOW()
WHERE item_id = $1
`

func (q *Queries) DeleteRecords(ctx context.Context, itemID int32) error {
	_, err := q.db.Exec(ctx, deleteRecords, itemID)
	return err
}
